In [1]:
#Arrays
import numpy

def arrays(arr):
    # complete this function
    # use numpy.array
    lis = (numpy.array(arr, float))
    res = lis[::-1]
    return res

    
arr = input().strip().split(' ')
result = arrays(arr)
print(result)

 1 2 3 4 -8 -10


[-10.  -8.   4.   3.   2.   1.]


In [3]:
#Shape and Reshape
import numpy as np
n = list(map(int, input().split()))
n_array = np.array(n)
print(np.reshape(n_array, (3, 3)))

 1 2 3 4 5 6 7 8 9


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
#Transpose and Flatten
import numpy as np
n, m = input().split()
M = []
for i in range(int(n)):  
    N = list(map(int, input().split()))
    M.append(N)
arr = np.array(M)
trans = np.transpose(arr)
print(trans)
print(arr.flatten())

 3 3 
 1 2 3
 4 5 6
 7 8 9


[[1 4 7]
 [2 5 8]
 [3 6 9]]
[1 2 3 4 5 6 7 8 9]


In [1]:
#### Concatenate
import numpy as np
n, m, p = input().split()
list1 = []
list2 = []
for i in range(int(n)):
    N = list(map(int, input().split()))
    list1.append(N)
for j in range(int(m)):
    M = list(map(int, input().split()))
    list2.append(M)
arr1 = np.array(list1)
arr2 = np.array(list2)
print(np.concatenate((arr1, arr2), axis = 0))

 4 3 2
 1 2
 1 2
 1 2
 1 2
 3 4
 3 4
 3 4


[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


In [3]:
#Zeros and Ones
import numpy as np
inp = tuple(map(int, input().split()))
print(np.zeros(inp, dtype = np.int))
print(np.ones(inp, dtype = np.int))

 3 3 3


[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [4]:
#Eye and Identity
import numpy as np
np.set_printoptions(sign = " ")
n, m = input().split()
print(np.eye(int(n), int(m)))



 3 3


[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [5]:
#Array Mathematics
import numpy as np

n, m = map(int, input().split())
A = np.array([list(map(int, input().split())) for _ in range(n)], int)
B = np.array([list(map(int, input().split())) for _ in range(n)], int)
print(A+B)
print(A-B)
print(A*B)
print(A//B)
print(A%B)
print(A**B)

 1 4
 1 2 3 4
 5 6 7 8


[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


In [6]:
#Floor, Ceil and Rint
import numpy as np
np.set_printoptions(sign=' ')
n = np.array(list(map(float, input().split())))
print(np.floor(n))
print(np.ceil(n))
print(np.rint(n))


 1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9


[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


In [7]:
#Sum and prod
import numpy as np
n, m = input().split()
lis = []
for _ in range(int(n)):
    N = list(map(int, input().split()))
    lis.append(N)
arr = np.array(lis)
Sum = np.sum(arr, axis = 0)
print(np.prod(Sum))

 2 2
 1 2
 3 4


24


In [1]:
#MIN and Max 
import numpy as np 
n, m = input().split()
lis = []
for _ in range(int(n)):
    N = list(map(int, input().split()))
    lis.append(N)
arr = np.array(lis)
Min = np.min(arr, axis = 1)
print(np.max(Min))

 4 2
 2 5
 3 7
 1 3
 4 0


3


In [3]:
#Mean, Var, and Std
import numpy as np
n, m = input().split()
lis = []
for _ in range(int(n)):
    N = list(map(int, input().split()))
    lis.append(N)
arr = np.array(lis)
print(np.mean(arr, axis=1))
print(np.var(arr, axis=0))
print(np.around((np.std(arr)), decimals=11))

 2 2
 1 2
 3 4


[1.5 3.5]
[1. 1.]
1.11803398875


In [4]:
#Dot and Cross
import numpy as np
n = int(input())
A = []
for _ in range(n):
    A_r = list(map(int, input().split()))
    A.append(A_r)
B = []
for _ in range(n):
    B_r = list(map(int, input().split()))
    B.append(B_r)
print(np.dot(np.array(A), np.array(B)))

 2
 1 2
 3 4
 1 2
 3 4


[[ 7 10]
 [15 22]]


In [1]:
#Inner and Outer
import numpy as np
A = np.array(list(map(int, input().split())))
B = np.array(list(map(int, input().split())))

print(np.inner(A, B))
print(np.outer(A, B))

 0 1
 2 3


3
[[0 0]
 [2 3]]


In [2]:
#Ploynomials
import numpy as np
A = list(map(float, input().split()))
n = int(input())
print(np.polyval(A, n))


 1 .1 2 3
 0


3.0


In [3]:
#Linear Algebra
import numpy as np
A = []
for _ in range(int(input())):
    A_r = list(map(float, input().split()))
    A.append(A_r)
print(np.around(np.linalg.det(A), decimals=2))

 2
 1.1 1.1
 1.1 1.1


0.0
